from setuptools import setup, find_packages

setup(
    name="knowledge-assistant",
    version="1.0.0",
    description="AI Personal Knowledge Assistant - Multi-agent system for organizing, retrieving, and synthesizing information",
    author="Your Name",
    author_email="your.email@example.com",
    url="https://github.com/yourusername/knowledge-assistant",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "pydantic>=2.5.0",
        "sqlalchemy>=2.0.23",
        "asyncpg>=0.29.0",
        "redis>=5.0.1",
        "cryptography>=41.0.7",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
        "python-multipart>=0.0.6",
        "httpx>=0.25.2",
        "aiohttp>=3.9.1",
        "sentence-transformers>=2.2.2",
        "numpy>=1.24.3",
        "python-dotenv>=1.0.0",
        "pydantic-settings>=2.1.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "pytest-asyncio>=0.21.0",
            "black>=23.10.0",
            "flake8>=6.1.0",
            "mypy>=1.6.0",
        ],
    },
    python_requires=">=3.10",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
)